#!/bin/sh

if [ "$JSELECT_HOME" == "" ]; then
  echo JSELECT_HOME not defined
  exit 1
fi

CLASSPATH=$JSELECT_HOME/jselect.d
CLASSPATH=$CLASSPATH:$JSELECT_HOME/jselect.d/jselect.jar
CLASSPATH=$CLASSPATH:$JSELECT_HOME/jselect.d/commons-logging-1.1.jar
CLASSPATH=$CLASSPATH:$JSELECT_HOME/jselect.d/log4j-1.2.14.jar
CLASSPATH=$CLASSPATH:$JSELECT_HOME/jselect.d/commons-cli-1.4.jar
CLASSPATH=$CLASSPATH:$JSELECT_HOME/jselect.d/commons-lang3-3.10.jar
CLASSPATH=$CLASSPATH:$JSELECT_HOME/jselect.d/postgresql-9.3-1104.jdbc41.jar
CMD="$JAVA_HOME/bin/java -classpath $CLASSPATH -Xmx128m jselect.JSelect $@"
eval $CMD
